#ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oracle-book
  namespace: dev
spec:
  rules:
    - host: api-oracle-book.guanweiming.com
      http:
        paths:
          - path: /
            backend:
              serviceName: oracle-book
              servicePort: 8888
---
#service
apiVersion: v1
kind: Service
metadata:
  name: oracle-book
  namespace: dev
spec:
  selector:
    app: oracle-book
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-book
  namespace: dev
spec:
  selector:
    matchLabels:
      app: oracle-book
  replicas: 1
  template:
    metadata:
      labels:
        app: oracle-book
    spec:
      containers:
        - name: pig
          image: registry.cn-beijing.aliyuncs.com/guanweiming/oracle-book:1.16
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-book
  namespace: dev
  labels:
    name: oracle-book




